name: Deploy
  
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - 'master'
      - 'release/**'
      - 'develop'
      - 'feature/**'
  workflow_dispatch:

jobs:
  list-versions:
    uses: ./.github/workflows/_list-versions.yml

  get-environment:
    needs: list-versions
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}    
    uses: ./.github/workflows/_get-environment.yml
   
  deploy:
    needs: 
      - list-versions
      - environment
    if: ${{ needs.list-versions.outputs.versions != '[]' && needs.list-versions.outputs.versions != '' }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        version: ${{ fromJson(needs.list-versions.outputs.versions) }}
    
    uses: ./.github/workflows/_docker-build.yml
    with:
      environment: ${{ needs.get-environment.outputs.environment }}
      version: ${{ matrix.version }}
      push: true
